apiVersion: v1
kind: Pod
metadata:
  name: gatling-report
spec:
  volumes:
    - name: reports
      persistentVolumeClaim:
        claimName: efs-claim
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
    - name: logs
      image: debian:12-slim
      command: ["cat"]
      tty: true
      resources:
        requests:
          cpu: "0.1"
          memory: 128Mi
        limits:
          cpu: "0.1"
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
      volumeMounts:
        - name: reports
          mountPath: /usr/local/share
